/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import abstractTableModel.ClientTableModel;
import abstractTableModel.EmployeeTableModel;
import abstractTableModel.ItemTableModel;
import dao.AddressDAO;
import dao.CarDAO;
import dao.CityDAO;
import dao.ClientDAO;
import dao.CombosDAO;
import dao.EmployeeDAO;
import dao.EmployeeFunctionDAO;
import dao.StateDAO;
import entidade.Address;
import entidade.Car;
import entidade.City;
import entidade.Client;
import entidade.Employee;
import entidade.EmployeeFunction;
import entidade.State;
import java.awt.Color;
import java.util.HashSet;
import java.util.Set;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.SwingConstants;
import tela.edit.EditClientFrm;
import tela.edit.EditEmployeeFrm;
import tela.register.RegisterClientFrm;
import tela.register.RegisterEmployeeFrm;
import tela.register.RegisterEmployeeFunctionFrm;
import tela.register.RegisterItemFrm;

/**
 *
 * @author minuzzi
 */
public class MainFrm extends javax.swing.JFrame {

    /**
     * Creates new form MainFrm
     */
    EmployeeTableModel employeeTableModel = new EmployeeTableModel();
    ClientTableModel clientTableModel = new ClientTableModel();
    ItemTableModel itemTableModel = new ItemTableModel(); 
    
    public MainFrm() {
        initComponents();
        Color backgroundColor = new Color(53,53,53);
        Color textColor = new Color(255,255,255);
        Color detailColor = new Color(235,164,23);
        Color btnColor = new Color (97,218,251);
        
        
        this.getContentPane().setBackground( backgroundColor );
        this.categoryCombo.setBackground( backgroundColor );
        this.categoryCombo.setForeground( detailColor );
        this.jPanel1.setBackground( backgroundColor );
        this.jPanel2.setBackground( backgroundColor );
        this.EmployeeFunctionBtn.setBackground( btnColor );
        this.EmployeeFunctionBtn.setForeground( textColor );
        this.clientBtn.setBackground( btnColor );
        this.clientBtn.setForeground( textColor );
        this.employeeBtn.setBackground( btnColor );
        this.employeeBtn.setForeground( textColor );
        this.itenBtn.setBackground( btnColor );
        this.itenBtn.setForeground( textColor );
        this.soBtn.setBackground( btnColor );
        this.soBtn.setForeground( textColor );
        this.editBtn.setBackground( btnColor );
        this.editBtn.setForeground( textColor );
        this.searchBtn.setBackground( btnColor );
        this.searchBtn.setForeground( textColor );
        this.searchField.setBackground( backgroundColor );
        this.searchField.setForeground( textColor );
        this.tblMain.setBackground( backgroundColor );
        this.tblMain.setForeground( textColor );
        
        CombosDAO comboDao = new CombosDAO();
        tblMain.setModel(employeeTableModel);
        editBtn.setVisible(true);
        
        JLabel lbl = new JLabel("Listagem");
        JLabel lbl2 = new JLabel("Cadastro");
        Icon icon = new ImageIcon(getClass().getResource("/assets/list-24.png"));
        Icon icon2 = new ImageIcon(getClass().getResource("/assets/plus-24.png"));
        lbl.setIcon(icon);
        lbl2.setIcon(icon2);
        
        lbl.setIconTextGap(5);
        lbl2.setIconTextGap(5);
        lbl.setHorizontalTextPosition(SwingConstants.RIGHT);
        lbl2.setHorizontalTextPosition(SwingConstants.RIGHT);

        this.jTabbedPane1.setTabComponentAt(0, lbl);
        this.jTabbedPane1.setTabComponentAt(1, lbl2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        searchBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        categoryCombo = new javax.swing.JComboBox<>();
        searchField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMain = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        editBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        employeeBtn = new javax.swing.JButton();
        clientBtn = new javax.swing.JButton();
        soBtn = new javax.swing.JButton();
        itenBtn = new javax.swing.JButton();
        EmployeeFunctionBtn = new javax.swing.JButton();
        toolIcon = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTabbedPane1.setBorder(null);
        jTabbedPane1.setForeground(new java.awt.Color(53, 53, 53));
        jTabbedPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPane1FocusGained(evt);
            }
        });

        searchBtn.setText("Procurar");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Categoria");

        categoryCombo.setForeground(new java.awt.Color(235, 164, 23));
        categoryCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Funcionário", "Cliente", "item", "Ordem de Serviço" }));
        categoryCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                categoryComboItemStateChanged(evt);
            }
        });
        categoryCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryComboActionPerformed(evt);
            }
        });

        tblMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblMain);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Procurar:");

        editBtn.setText("Editar Funcionário");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(categoryCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(editBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listagem", jPanel2);

        jPanel1.setForeground(new java.awt.Color(53, 53, 53));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(235, 164, 23));
        jLabel2.setText("Funcionário");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(235, 164, 23));
        jLabel4.setText("Cliente");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(235, 164, 23));
        jLabel5.setText("Ordem Serviço");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(235, 164, 23));
        jLabel6.setText("Item");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(235, 164, 23));
        jLabel7.setText("Cargo / Ocupação");

        employeeBtn.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        employeeBtn.setText("+");
        employeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeBtnActionPerformed(evt);
            }
        });

        clientBtn.setBackground(new java.awt.Color(97, 218, 251));
        clientBtn.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        clientBtn.setText("+");
        clientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientBtnActionPerformed(evt);
            }
        });

        soBtn.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        soBtn.setText("+");

        itenBtn.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        itenBtn.setText("+");
        itenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itenBtnActionPerformed(evt);
            }
        });

        EmployeeFunctionBtn.setBackground(new java.awt.Color(97, 218, 251));
        EmployeeFunctionBtn.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        EmployeeFunctionBtn.setText("+");
        EmployeeFunctionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeFunctionBtnActionPerformed(evt);
            }
        });

        toolIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/job-64.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(155, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(itenBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(EmployeeFunctionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(81, 81, 81)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(clientBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel4))
                    .addComponent(soBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(11, 11, 11)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(employeeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jLabel2)))
                        .addGap(0, 127, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(toolIcon)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EmployeeFunctionBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                            .addComponent(clientBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(employeeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(itenBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(soBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(toolIcon)
                        .addContainerGap())))
        );

        jTabbedPane1.addTab("Cadastro", jPanel1);

        jLabel8.setFont(new java.awt.Font("Ubuntu Light", 3, 60)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(97, 218, 251));
        jLabel8.setText("MinuzziMEC");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(196, 196, 196))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBtnActionPerformed

    private void categoryComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryComboActionPerformed

    private void employeeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeBtnActionPerformed
        new RegisterEmployeeFrm(this, true).setVisible(true);
    }//GEN-LAST:event_employeeBtnActionPerformed

    private void EmployeeFunctionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeFunctionBtnActionPerformed
        new RegisterEmployeeFunctionFrm(this, true).setVisible(true);
    }//GEN-LAST:event_EmployeeFunctionBtnActionPerformed

    private void clientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientBtnActionPerformed
        new RegisterClientFrm(this, true).setVisible(true);
    }//GEN-LAST:event_clientBtnActionPerformed

    private void categoryComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_categoryComboItemStateChanged
        if(categoryCombo.getSelectedIndex() == 0){
            tblMain.setModel(employeeTableModel);
            editBtn.setText("Editar Funcionário");
        } else if (categoryCombo.getSelectedIndex() == 1){
            tblMain.setModel(clientTableModel);
            editBtn.setText("Editar Cliente");
        } else if (categoryCombo.getSelectedIndex() == 2){
            tblMain.setModel(itemTableModel);
            editBtn.setText("Editar Item");
        }
    }//GEN-LAST:event_categoryComboItemStateChanged

    private void itenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itenBtnActionPerformed
        new RegisterItemFrm(this, true).setVisible(true);
    }//GEN-LAST:event_itenBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        int position = (int)(tblMain.getValueAt(tblMain.getSelectedRow(), 0));
        if(tblMain.getSelectedRow() != -1){
            
            if(categoryCombo.getSelectedIndex() == 0){
            EmployeeDAO employeeDao = new EmployeeDAO();
            Employee employee = employeeDao.returnEmployee(position);        
            new EditEmployeeFrm(this, true,
                    (int) tblMain.getValueAt(tblMain.getSelectedRow(), 0),
                    employee.getEmail(),
                    employee.getName(),
                    employee.getFunction_id(),
                    employee.getSituation()).setVisible(true);
            
            } else if (categoryCombo.getSelectedIndex() == 1){
                ClientDAO clientDao = new ClientDAO();
                Client client = clientDao.returnClient(position);

                AddressDAO addressDao = new AddressDAO();
                Address  address = addressDao.returnAddress(position);
    //            Address addressId = addressDao.returnAddressId();

                CityDAO cityDao = new CityDAO();
                City  city = cityDao.returnCity(position);

                StateDAO stateDao = new StateDAO();
                State  state = stateDao.returnState(position);
                
                CarDAO carDao = new CarDAO();
                Car car = carDao.returnCar(position);
                
                int addressID = address.getId();
                new EditClientFrm(this, true,
                    (int) tblMain.getValueAt(tblMain.getSelectedRow(), 0),
                        addressID,
                        address.getCity_id(),
                        state.getId(),
                        car.getId(),
                        car.getClient_id(),
                        client.getName(), 
                        client.getEmail(), 
                        client.getCpf(), 
                        address.getStreet(),
                        address.getNeighborhood(), 
                        address.getNumber(),
                        car.getName(),
                        car.getModel(),
                        car.getYear(),
                        car.getCarPlate(),
                        car.getDescription_problem()).setVisible(true);
            } else if (categoryCombo.getSelectedIndex() == 2){

            } else if (categoryCombo.getSelectedIndex() == 3){

            }    
        } else {
            JOptionPane.showMessageDialog(null, "Você precisa selecionar algo na tabela antes.");
        }

            
    }//GEN-LAST:event_editBtnActionPerformed

    private void jTabbedPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane1FocusGained
        if(categoryCombo.getSelectedIndex() == 0){
            EmployeeTableModel etm = (EmployeeTableModel) tblMain.getModel();
            etm.updateData();
        } else if(categoryCombo.getSelectedIndex() == 1){
            ClientTableModel etm = (ClientTableModel) tblMain.getModel();
            etm.updateData();
        } else if(categoryCombo.getSelectedIndex() == 2){
            ItemTableModel etm = (ItemTableModel) tblMain.getModel();
            etm.updateData();
        }
    }//GEN-LAST:event_jTabbedPane1FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EmployeeFunctionBtn;
    private javax.swing.JComboBox<String> categoryCombo;
    private javax.swing.JButton clientBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JButton employeeBtn;
    private javax.swing.JButton itenBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchField;
    private javax.swing.JButton soBtn;
    private javax.swing.JTable tblMain;
    private javax.swing.JLabel toolIcon;
    // End of variables declaration//GEN-END:variables
}
